### ISSUE TITLE
Build fails on Windows

### ISSUE THREAD

**Issue by hovatterz** [hovatterz/light#3]
x-post from: http://en.sfml-dev.org/forums/index.php?topic=6635.msg54234#msg54234

**Comment by seanballais** [comment]
Does this bug still occur (in 2015)?

**Comment by eXpl0it3r** [comment]
Seems to build fine for me.

**Comment by seanballais** [comment]
I guess this bug report should be removed then?

**Comment by hovatterz** [comment]
Closed!
